import semantics.Compare;
import org.parse4j.*;
import org.parse4j.callback.*;
import java.util.*;
public class MilestoneSimilarity {
	public static Hashtable<String,ParseObject> standardMilestones;
	public static int num=0;
	private static List<ParseObject> allCustomMilestones = new ArrayList<ParseObject>();
	private static List<ParseObject> customTitles = new ArrayList<ParseObject>();
	
	public static double getSimilarity(String sentence1,String sentence2){
		Compare c=new Compare(sentence1,sentence2);
		return c.getResult();
	}
	
	public static void print(Object name){
		System.out.println(name);
	}
	
	public static void getStandardTitles(){
		ParseQuery<ParseObject> queryStandard = ParseQuery.getQuery("StandardMilestones");
		queryStandard.limit(1000);
		queryStandard.findInBackground(new FindCallback<ParseObject>() {
		    public void done(List<ParseObject> milestoneList, ParseException e) {
		        if (e == null) {
		        	Hashtable<String,ParseObject> titleToStandardMilestone = new Hashtable<String, ParseObject>();
		            for (ParseObject standardMilestone : milestoneList){
		            	titleToStandardMilestone.put((String)standardMilestone.get("title"),standardMilestone);
		            }
		            setStandardMilestones(titleToStandardMilestone);
		            //Debug
		            print("Standard Milestones: " +titleToStandardMilestone);
		            print("Count of Standard Milestones: " +titleToStandardMilestone.size());
		            getCustomMilestones();
		        } else {
		            print("Error: " + e.getMessage());
		        }
		    }
		});
	}
	
	public static void getCustomMilestones(){
		final ParseQuery<ParseObject> query = ParseQuery.getQuery("MilestoneAchievements");
		query.limit(1000);
		query.whereNotEqualTo("customTitle","${He}'s born and is beautiful!");
		query.whereEqualTo("isSkipped", false);
		query.whereEqualTo("isPostponed", false);
		query.whereDoesNotExist("standardMilestoneId");
		query.whereExists("customTitle");
		query.findInBackground(getAllCustomMilestones());
	}
	
	public static void compareWithStandard(List<ParseObject> milestoneList){
		for (ParseObject milestone : milestoneList){
			getMostSimilarToMilestone(milestone);
		}
	}
	
	public static void setStandardMilestones(Hashtable<String,ParseObject> list){
		standardMilestones=list;
	}
	
	public static Hashtable<String,ParseObject> getStandardMilestones(){
		return standardMilestones;
	}
	
	public static int skip=0;
	public static FindCallback<ParseObject> getAllCustomMilestones(){
	    return new FindCallback<ParseObject>(){
	        public void done(List<ParseObject> objects, ParseException e) {
	            if (e == null) {
	                allCustomMilestones.addAll(objects);
	                int limit =1000;
	                if (objects.size() == limit){
	                    skip = skip + limit;
	                    ParseQuery<ParseObject> recursiveQuery = new ParseQuery<ParseObject>("MilestoneAchievements");
	                    recursiveQuery.skip(skip);
	                    recursiveQuery.limit(limit);
	                    recursiveQuery.findInBackground(getAllCustomMilestones());
	                }
	                //We have a full PokeDex
	                else {
	                	print("Total custom milestones found: " +allCustomMilestones.size());
	                    compareWithStandard(allCustomMilestones);
	                }
	            }
	            else {print(e);
	            }
	        };
	    };
	}
	
	public static void getMostSimilarToMilestone(ParseObject achievement){
		String customTitle=(String)achievement.get("customTitle");
		List<String> standardTitles=Collections.list(getStandardMilestones().keys());
		for(String standardTitle : standardTitles){
			double sim=getSimilarity(customTitle,standardTitle);
			if(sim>0.85){
				ParseObject simObject = new ParseObject("Similarities");
		        simObject.put("achievement1",achievement);
		        simObject.put("standardMilestone",getStandardMilestones().get(standardTitle));
		        simObject.put("title1",customTitle);
		        simObject.put("title2",standardTitle);
		        simObject.put("similarityScore",sim);
		        print("**********Saved: "+ ++num+"**********");
		        print(customTitle+"------"+standardTitle);
		        //simObject.saveInBackground();
			}
		}
	}
	
	public static List<String> hardCodedStandardTitles=Arrays.asList("First time ${he} dumps a bowl of Cheerios (or another cereal) on the floor",
	                              "First family holiday card",
	                              "First time ${he} goes up an entire staircase (and wants to do it again and again)",
	                              "First pancakes",
	                              "First burp",
	                              "First time ${he} puts on shoes and socks independently",
	                              "First time ${he} watches television",
	                              "First time sick",
	                              "First time you think, ${He} is less like an alien and more like a little person",
	                              "First time Mom does a paranoid quintuple-check that ${he}s alive",
	                              "First time ${he} moves ${his} head to follow your movement -- predicting where youll go",
	                              "First time ${he} slithers",
	                              "First time on a see-saw",
	                              "First time creamy poo turns into a turd",
	                              "First time ${he} makes friends with the baby of a friend of yours ",
	                              "First (unforgettably foul) post-solids poop",
	                              "First time ${he} eats something ${he} shouldnt",
	                              "First real solid food",
	                              "First time ${he} recites alphabet",
	                              "First time ${he} glues ${his} fingers together (and panics)",
	                              "First time ${he} sticks out ${his} tongue",
	                              "First time ${he} recognizes ${his} name written",
	                              "First clap",
	                              "First time ${he} pees on you, deliberately",
	                              "First time ${he} takes off ${his} own sock",
	                              "First time ${he} knows the names and time periods of all the dinosaurs!",
	                              "First half wave (wave with a closed fist)",
	                              "First time you feel true remorse for having ever judged the parent of a screaming child",
	                              "First time ${he} can put on a shirt and pants independently",
	                              "Buy your third stroller",
	                              "First time ${he} can see people across the room",
	                              "First time you catch ${him} manipulating you",
	                              "First time ${he} becomes obsessed with potty language",
	                              "First time ${he} buttons up ${his} shirt",
	                              "First time ${he} walks - without help",
	                              "First toddler gym class",
	                              "First time ${he} bears weight on legs (while being held)",
	                              "First time ${he} sticks out ${his} tongue in response to yours",
	                              "First time you can recognize what the different cries mean",
	                              "First time ${he} shows disapproval of a food ${he}s given",
	                              "First crawl",
	                              "First time ${he} wakes up on ${his} own... without crying",
	                              "First time brushing ${his} teeth",
	                              "First time ${he} uses scissors",
	                              "First time riding in a baby seat on a bicycle",
	                              "First trip to a childrens museum",
	                              "First day of first summer camp!",
	                              "First time ${he} puts ${his} toys away",
	                              "First time you put a hat on ${him}... and ${he} takes it off",
	                              "First time ${he} faints from throwing a tantrum",
	                              "First time verbally rejecting mom or dad (I dont want you! Can you go away?)",
	                              "${He} starts saying NO to everything",
	                              "First time, since ${his} birth, that you and your partner discuss something that doesnt have to do with your child.",
	                              "First time ${he} recognizes a stuffed animal",
	                              "First time ${he} falls asleep on Mom -- and Mom also falls asleep",
	                              "First time you and Mom talk to each other in baby-talk",
	                              "First time ${he} plays with ${him}self calmly for 1 hour ",
	                              "First time ${he} eats ${his} own hand",
	                              "First time you can differentiate ${his} cries",
	                              "First time ${he} cruises on couches, cribs, anything",
	                              "First time eating a blueberry",
	                              "First time stands on ${his} own holding onto something for two minutes",
	                              "First focused stare, for more than 3 minutes straight",
	                              "Sat up in bumbo seat",
	                              "First time ${he} flips you off (without meaning it)",
	                              "First time ${he} rolls",
	                              "First weeeee down a slide",
	                              "First time you use the airplane trick to give ${him} food",
	                              "First Staycation with Dad",
	                              "First time on a train",
	                              "First time ${he} reaches for something (other than Moms breast)",
	                              "First time ${he} bangs ${his} head on the floor in frustration",
	                              "First sibling hand holding",
	                              "First time ${he} pulls ${him}self to standing using furniture",
	                              "First bottom tooth",
	                              "First time you claim a sixth sense of knowing when ${he}s about to cry or almost be injured",
	                              "First yawn",
	                              "First time ${he} uses a sippy cup without help",
	                              "Figures out how to use remote to turn TV on and off",
	                              "First poop in the bath",
	                              "First spitup",
	                              "First time someone tells you, Enjoy every minute of these days, before you know it, ${he} will be grown up",
	                              "First time you think you want another baby",
	                              "First time ${he} cries when adults ${he} doesnt know come up to ${him}",
	                              "First time ${he} throws something",
	                              "First time after birth Mom starts losing hair: postpartum hair loss",
	                              "First time you realize ${his} head stopped jiggling",
	                              "Gets a real bed!",
	                              "First time ${he} reads Frog and Toad",
	                              "First time Dad can recognize what the different cries mean",
	                              "First time ${he} responds to ${his} name",
	                              "Buy your second stroller",
	                              "First time ${he} draws ${his} preschool teacher, anatomically correct",
	                              "First time you do a paranoid quintuple-check that ${he}s alive",
	                              "First favourite color",
	                              "First time you notice ${he} enjoys looking at contrasting colors",
	                              "First time ${he} points to your mouth when you say the word mouth",
	                              "First poo on a real toilet",
	                              "First time you realize ${he} loves emptying buckets of objects",
	                              "First real haircut",
	                              "First time ${he} makes a face because ${his} food is too hot",
	                              "Wears size 3-6mos!",
	                              "First time ${he} makes up songs with rhyming words. Sings them too loudly.",
	                              "First time ${he} scratches you ",
	                              "First fit of rolling and laughing",
	                              "First time ${he} cockblocks you.",
	                              "First time ${he} makes a funny face, voluntarily (not as a reaction)",
	                              "First time you realize ${he} doesnt put everything ${he} touches in his mouth ",
	                              "First Donut",
	                              "First time ${he} takes food out of ${his} mouth to replace with something ${he} wants more.",
	                              "First time you realize that ${he} prefers one of your breasts over the other",
	                              "First time ${he} cries and you suspect it is only because ${he} wants attention",
	                              "First time she gets her ears pierced",
	                              "First time ${he} licks everything",
	                              "First trip to a pumpkin patch",
	                              "First time ${he} stands on ${his} own -- and turns around",
	                              "The falling down and bumping the head phase begins.",
	                              "First time you take ${him} to the doctor for no reason ",
	                              "First time ${he} eats with a fork",
	                              "${His} first singalong",
	                              "First time ${he} goes up or down the stairs",
	                              "First time ${he} loves going on the swings",
	                              "First time falls asleep in very uncomfortable position",
	                              "First time climbs into ${his} stroller by himself.",
	                              "First time throws out ${his} own stinky diaper",
	                              "First time ${he} puts objects into a container",
	                              "First time ${he} says grandma and grandpa",
	                              "Said mmm! While eating",
	                              "First time being swaddled",
	                              "First time ${he} lays on a mat",
	                              "First time ${he} answers the phone",
	                              "${He} eats almost anything, even if its not food!",
	                              "First time ${he} looks at you... and vomits",
	                              "First time ${he} ate a crayon",
	                              "First time ${he} wears a hat",
	                              "First top tooth",
	                              "First time ${he} becomes obsessed with closing doors",
	                              "First time you suspect ${he} actually understands the adult conversation ${he}s listening to",
	                              "First time you realize ${he} enjoys exersaucers and jumpers",
	                              "First broken leg",
	                              "First time ${he} rolls out the toilet paper",
	                              "${He} knows ${his} name",
	                              "First time bites dad",
	                              "First interstate trip!",
	                              "First time eating a tomato",
	                              "First time ${he} looses a glove",
	                              "First choking scare",
	                              "First time ${he} sits in stroller (bottom part, without the car seat)",
	                              "First time ${he} hides something of yours",
	                              "First time ${he} babbles mamamamama or papapapapa -- getting ready to tell you your new names!",
	                              "First time ${he} loves Dr. Seuss books",
	                              "First time ${he} eats by himself",
	                              "First time ${he} recognizes you",
	                              "First time ${he} goes down the slide",
	                              "First time you hold ${him} and imagine dropping ${him}",
	                              "First real cough",
	                              "First feature length film in the theater",
	                              "First high one",
	                              "First time you give ${him} food to distract ${him}",
	                              "First time ${he}s jealous of the dog",
	                              "First time ${he} pretends ${he}s the teacher",
	                              "First time your breasts leak",
	                              "First time ${he} soaks through regular diapers at night",
	                              "First time you can tell ${his} eye colour ",
	                              "First time goes in the toilet",
	                              "First time you realize that ${he} is ticklish",
	                              "First time ${he} vomits on you ",
	                              "First time you realize ${he} behaves differently around different people",
	                              "${He} knows the colors",
	                              "First time ${he} really goes looking for something (ie, under the couch)",
	                              "First time wears a backpack",
	                              "First time imitates the sound of a machine",
	                              "First time ${he} picks ${his} nose",
	                              "First trip to a farm",
	                              "First time you realize ${he} prefers being around the family - theyre no longer strangers",
	                              "First trip to the neighbors house alone",
	                              "First time ${he} climbs up the couch",
	                              "First time you and Dad talk to each other in baby-talk",
	                              "You enter the Has anyone seen ${him}? stage",
	                              "First time ${he} falls in love with someone ${he} sees ",
	                              "First time ${he} sits up without anyones help -- for just a moment",
	                              "First time ${he} uses a straw properly",
	                              "First time ${he} does the peepee dance",
	                              "First time ${he} grasps your hand tightly",
	                              "First time ${he} tests you",
	                              "First time ${he} keeps ${his} legs up in the air for an extended period, while laying on ${his} back",
	                              "First time Mom claims a sixth sense of knowing when ${he}s about to cry or almost be injured",
	                              "First time ${he} chokes on something you gave him (food or otherwise)",
	                              "First time ${he} can feed himself with a bottle",
	                              "First trip to the library",
	                              "First time stands up without holding on to anything",
	                              "First time you realize that ${he} prefers one of Moms breasts over the other",
	                              "First time eating strawberry ice cream",
	                              "First time ${he} gets how to turn knobs",
	                              "First time draws on furniture/walls.",
	                              "First time ${he} owns you and knows it",
	                              "Acquires a slight stutter",
	                              "First time walks around crib all alone (while holding onto the edge)",
	                              "First time youre not sure if ${he} is laughing or crying",
	                              "First time ${he} wants a random snack youre eating... and you put some on your finger and give it to ${him}",
	                              "First time ${he} found something you hid from ${him}",
	                              "First time ${he} writes ${his} own name",
	                              "First time ${he} imitates speaking on the phone",
	                              "First time ${he} turns the page in a book",
	                              "First time ${he} says I love you",
	                              "First time ${he} falls asleep while drinking from your breast",
	                              "First responsive smile",
	                              "First time ${he} touches ${him}self inappropriately. (But its actually appropriate!)",
	                              "First time you fly ${him} around like ${he}s an airplane",
	                              "First time ${he} plays in the snow",
	                              "First picture with the Easter Bunny!",
	                              "First time ${he} watches you brush your teeth - and is fascinated by it",
	                              "First time ${he} notices ${his} own shadow",
	                              "First conversation with him when you talk and he babbles back responsively",
	                              "First time ${he} puts ${his} complete hand into ${his} mouth",
	                              "First time to sit up alone (with boppy)",
	                              "First time on grass",
	                              "First time took a bottle from dad",
	                              "First time ${he} clasps ${his} hands together",
	                              "First fall at the playground",
	                              "First time you hold ${him} and ${he} tries to suck your breast ",
	                              "First time ${he} invents his own word and keeps using it",
	                              "First selfie together",
	                              "First time you let ${him} cry it out -- for real (not going in!)",
	                              "First time ${he} smells food",
	                              "You now hate any house pets that preexisted your child",
	                              "First time you change ${his} diaper",
	                              "First time you realize that ${his} laugh is the best sound in the world",
	                              "First time ${he} waters the flowers",
	                              "First time you say to your partner, Did you wash your hands? when youre about to touch ${him}",
	                              "First time drinkimg from a water fountain",
	                              "First time ${he} paints and colors by number",
	                              "First time ${he} can clap",
	                              "First time Moms breasts leak",
	                              "First time in a bouncy castle",
	                              "First soapy hair",
	                              "First laugh, from deep in ${his} belly",
	                              "First dance class",
	                              "First time ${he} hugs another baby",
	                              "First time ${he} beats Dad in a game of Connect Four",
	                              "First time ${he} vomits on ${him}self ",
	                              "First ride on a three-wheeled scooter",
	                              "First explosive poo",
	                              "First giggle",
	                              "First time ${he} waddles",
	                              "First time ${he} recognizes Mom",
	                              "First board game",
	                              "First time ${he} babbles to ${him}self for 30 minutes straight",
	                              "First sibling crying together",
	                              "First time ${he} eats a flower",
	                              "First time ${he} sees Mom holding a friends baby. Oh, the rage!",
	                              "First time climbs up a slide by himself",
	                              "First time ${he} coughs on command, to get laughs",
	                              "First time she hates wearing barrettes",
	                              "First time you carry with you a portable toilet",
	                              "First time ${he} has an irrational fear. Perhaps of stuffed animals.",
	                              "Rolls over front to back",
	                              "First time ${he} climbs up steps, but is unable to climb down (and cries pitifully when stuck!)",
	                              "First time ${he} recognized and points to a plane",
	                              "First time he hides because hes doing something he shouldnt",
	                              "First time ${he} blows a raspberry (makes a farting sound with ${his} mouth)",
	                              "First time ${he} says yes when you ask ${him} if ${he} did poopy",
	                              "First time youre comfortable putting ${him} on the bed, without pillows on ${his} sides",
	                              "First time she wears barrettes in her hair",
	                              "First time ${he} uses a spoon",
	                              "First time ${he} responds to a no",
	                              "First time ${he} discovers ${his} feet (stares at them)",
	                              "First time ${he} hates being strapped into the car seat",
	                              "First time ${he} comes home from school with a face covered in ink",
	                              "First time you can eat in a restaurant again",
	                              "Second word",
	                              "First time ${he} talks about having friends",
	                              "First time ${he} grabs everything in sight, nonstop",
	                              "Took a bath with mommy ",
	                              "First potty joke",
	                              "First time ${he} looks straight in your eyes, for more than a momentary glance.",
	                              "First time ${he} wears 12-18 mos clothes",
	                              "First time ${he} purposefully imitates you",
	                              "First time you realize ${he}s learning more by touching than tasting",
	                              "First time ${he} notices a non-toy object... and turns it into a toy",
	                              "First time ${he} spells ${his} own name",
	                              "First time ${he} stands on ${his} own, while holding onto something stationary for support to stay up",
	                              "First time ${he} reaches for Dads nose",
	                              "First time he discovers the pleasure of running",
	                              "First time feeds dog",
	                              "First time holding dads finger",
	                              "First time sharing food",
	                              "First fake cough",
	                              "First time ${he} loses interest in using the pacifier",
	                              "First time ${he} reaches for Moms breast",
	                              "First half-smile",
	                              "First time ${he} eats your hand",
	                              "First visit to the dentist",
	                              "First time ${he} asks if ${his} little sibling can go away",
	                              "First time ${he} realizes that magnets are not like other objects",
	                              "First time shivers from cold",
	                              "First time ${he} does a somersault",
	                              "First time ${he} lays on your chest and sleeps",
	                              "First time ${he} gets out of his bed, walks into your bedroom while youre sleeping, walks over to the bed, and climbs up in with you",
	                              "First time ${he} army crawls, like a true marine",
	                              "First time Dad can differentiate ${his} cries",
	                              "First time ${he} walks on a balance beam",
	                              "${He} falls in love with Mo Willemss books",
	                              "First time you realize ${he} likes tummy time",
	                              "First time ${he} is eating(-ish) and takes ${his} spoon to dip it into the bowl/plate for more, on ${his} own, without prompting",
	                              "First sat on Santas lap",
	                              "First time ${he} counts to 100",
	                              "First time ${he} tries to eat dirt",
	                              "First time ${he} plays Patty Cake",
	                              "First pee pee in the potty",
	                              "First time sayin up very clearly",
	                              "First St. Patricks Day",
	                              "First fight at recess",
	                              "First fall off a bike",
	                              "First time ${he} tries to eat sand at the beach or park",
	                              "First time you realize that ${his} favorite game is pulling all the tissues out of a tissue box",
	                              "First time putting ${his} toes in the ocean",
	                              "First time youre walking with your baby in public and another dad with his baby gives you The Nod",
	                              "First time holding moms finger",
	                              "First time ${he} walks - with help",
	                              "First time ${he} does the peepee dance while looking you in the face and telling you ${he} doesnt have to go.",
	                              "First time you or your partner cleans out ${his} earwax with a q-tip",
	                              "First telephone conversation",
	                              "First time ${he} picks your nose",
	                              "First time ${he} does the pincer grasp (picking up small objects with the thumb and forefinger)",
	                              "First sun tan",
	                              "Took multiple steps unassisted ",
	                              "First time ${he} babbles to ${him}self",
	                              "First time ${he} eats yogurt",
	                              "First time sitting in high chair",
	                              "Meets little sibling for the first time, melting your heart completely",
	                              "First time Mom freaks out over nothing",
	                              "First time ${he} can walk while pushing a push toy",
	                              "${He} outgrows the baby bath tub",
	                              "First exchange: he hands you something and you give him something back",
	                              "First time ${he} shows ${he} is thinking about another person",
	                              "First time waters the plants by ${him}self",
	                              "First ride on a tricycle!",
	                              "First time ${he} kisses ${his} stuffed animal goodbye",
	                              "First time you go outside the house (excluding for essentials and work) since ${he} was born",
	                              "First time ${he} holds the bottle while drinking",
	                              "First time ${he} delays leaving the house",
	                              "First time you notice that ${he} can walk smoothly, heel to toe, like a grown-up",
	                              "Throws things, just to upset you. (Stay cool!)",
	                              "First time jumping on bed",
	                              "First time ${he} opens and closes a door repeatedly",
	                              "First play date",
	                              "First time ${he} draws with a crayon",
	                              "Learns that ${he} is going to have a little brother/sister",
	                              "First time ${he} shakes head no when you offer ${him} something",
	                              "Went from belly to sitting all by herself",
	                              "First time in the pool",
	                              "First time cooing instead of grunting",
	                              "First time ${he} stands on ${his} own -- and turns ${his} head",
	                              "First time ${he} falls off potty, mid-poo",
	                              "First black eye",
	                              "First time ${he} starts grabbing everything in sight nonstop",
	                              "First pony ride",
	                              "First time someone else watches ${him} so you can go out for the night",
	                              "First time he likes a girl and touches her face",
	                              "First time ${he} makes simple patterns with blocks or cubes",
	                              "First day of kindergarten",
	                              "First time ${he} washes the dishes",
	                              "First time ${he} pees on Mom",
	                              "First time you judge a parent by which stroller they have",
	                              "First time ${he} repeats your 4-letter words. Sh*t.",
	                              "First time using left hand to rub eyes",
	                              "First girlfriend",
	                              "First picture with dad",
	                              "First time ${he} tries to pick up the family pet",
	                              "First potty training regression",
	                              "First time ${he} giggles in response to a tickle",
	                              "First out loud laugh",
	                              "First time points to an object in a book when you ask ${him} where it is",
	                              "First time ${he} plays pretend, playing with invisible objects",
	                              "First time ${he} claps when ${he} is done making a poo on ${his} potty",
	                              "First time ${he} says mom clearly and not accidentally",
	                              "First time in an airplane",
	                              "First bottled, pumped breast milk",
	                              "First time ${he} hands stuff to you to take",
	                              "First time ${he} wakes up because the movie youre watching is too loud.",
	                              "First time ${he} is sick whilst you are sick yourself",
	                              "FIrst time taking a walk with ${him} outside",
	                              "First time pressing the lift button",
	                              "First time ${he} pretends to play musical instruments (especially guitar)",
	                              "First time ${he} smiles in response to taking ${his} photo",
	                              "First meal with the family",
	                              "Holds ${his} head up on ${his} own",
	                              "First favourite toy",
	                              "First time you think to yourself, Wow, ${he}s actually a human",
	                              "First time ${he} imitates you reading a book",
	                              "First time ${he} sleeps 4 hours without interruption",
	                              "First time ${his} outfit is changed 5 times in one day",
	                              "First time wears sunglasses",
	                              "First time eats in public",
	                              "First sibling sing-a-long",
	                              "First tea party",
	                              "First time ${he} plays with a toy, coordinating both hands",
	                              "First time you take ${him} swimming",
	                              "First time ${he} builds space ships",
	                              "First time ${he} imitates a song with ${his} voice",
	                              "First time you wonder if ${he}s autistic",
	                              "You notice ${his} cry has changed from involuntary infant cry to something more intentional",
	                              "Got up in knees pre-crawling position",
	                              "First sneeze",
	                              "First time ${he} smiles in response to a tickle",
	                              "First time ${he} points at what ${he} wants",
	                              "First time ${he} is more interested in the spoon than in dinner!",
	                              "First time ${he} keeps ${his} head up straight without bouncing around",
	                              "First time cleans up by ${him}self",
	                              "First time ${he} puts on and zips up ${his} own coat independently",
	                              "First time you notice ${he} is attracted by bright colors",
	                              "First time opening a drawer",
	                              "First time ${he} brings you a book because ${he} wants you to read to ${him}",
	                              "First time you wonder, Why on earth does ${he} find this so funny?",
	                              "First crush",
	                              "First time ${he} enters sleep regression, a stop in sleeping after the first calm months",
	                              "First trip to the circus!",
	                              "Stacks blocks while playing",
	                              "First time walks up steps without help",
	                              "Gives up the bottle",
	                              "First time Dad changes ${his} diaper",
	                              "First time ${he} can walk while carrying something",
	                              "First time ${he} plays in the sand",
	                              "First time ${he} accidentally opens the front door and just wanders out all alone!",
	                              "First baby dance party",
	                              "${He} weighs 20 lbs!",
	                              "First time ${he} says uh-oh!",
	                              "First time ${he} squeezes your hand",
	                              "First meal when nothing winds up on the floor",
	                              "First time ${he} kicks a ball",
	                              "First sunburn",
	                              "First hiccup",
	                              "First day in toddler bed",
	                              "First you realize ${he} really loves ${his} pound-a-peg",
	                              "First time ${he} plays with ${him}self, while relaxing on a mat",
	                              "Second top tooth",
	                              "${He} suddenly becomes a picky eater",
	                              "First time ${he} says a word, for real, clearly and non-accidentally",
	                              "First time ${he} gives you a bug or worm as a present",
	                              "First mischievous look, as ${he}s about to do something ${he} knows ${he} shouldnt",
	                              "First time ${he} poos immediately after you change ${him}",
	                              "First time ${he} recognizes a word and says it outloud",
	                              "First time ${he} loves Elmo",
	                              "First time you realize that ${he}s attached to ${his} transitional object",
	                              "First time you put ${him} on ${his} tummy, to help ${him} lift ${his} head--and ${he} hates it--but you continue doing it",
	                              "First sleep in her own room.",
	                              "First time gets roseola",
	                              "First time can recognize immediate family member by name",
	                              "First time ${he} vomits while wearing a pacifier, making the pacifier and the vomit together spit out",
	                              "First time ${he} reads Cat in the Hat",
	                              "First time ${he} is clearly stimulated by high-contrast, black-and-white pattern",
	                              "First time on the swing",
	                              "First Infection",
	                              "${He} begins to ask why? incessantly",
	                              "First sponge bath",
	                              "First time ${he} says ${his} own name",
	                              "First time eating broccoli",
	                              "First time ${he} thinks that everything looks like a train",
	                              "First time you try the cry it out method (aka Ferber) - successfully",
	                              "Perfectly says YES",
	                              "First time ${he} understands the everyday no",
	                              "Learns how to skip",
	                              "You realize ${he} is consistently responding to ${his} name",
	                              "First time ${he} eats ${his} own arm",
	                              "First time ${he} understands bye bye",
	                              "First sports team obsession.",
	                              "First time figures out how the volume control works",
	                              "First time ${he} turns on electronics",
	                              "First time shuts ${him}self behind a door intentionally",
	                              "First time bites mom",
	                              "First time blows on ${his} food",
	                              "First time ${he} feeds pigeons",
	                              "Sings simple songs",
	                              "First time you notice ${he} feels jealousy",
	                              "First time ${he} cries with tears",
	                              "First time ${he} reaches to drink your wine or beer",
	                              "First time ${he} reaches for things deliberately",
	                              "First time chewing on a nipple ",
	                              "First time ${he} grabs your hair",
	                              "First time ${he} throws food from the high chair",
	                              "First time after birth you starts losing hair: postpartum hair loss",
	                              "First time you notice that ${he}s grown a lot of hair since birth",
	                              "${He} eats three meals each day",
	                              "First time playing with bubble wrap",
	                              "First time ${he} puts stuff in ${his} mouth",
	                              "First time ${he} empties out a container... and puts its contents back in",
	                              "First time ${he} becomes obsessed with making the raspberry sound",
	                              "First time riding a dog",
	                              "First time you want to jump out of the window after hearing the same lullabies over and over, one time too many.",
	                              "First time ${he} hands you a poop as a gift",
	                              "First time changing ${him} becomes a tug of war",
	                              "First time ${he} loves to push the stroller",
	                              "First stretch while asleep",
	                              "First time you see one of your characteristics in ${him}",
	                              "First fart ",
	                              "${His} first drink of water",
	                              "First time pressing the traffic light button",
	                              "First time ${he} walks more than ten steps assisted",
	                              "${He} knows the letters and numbers",
	                              "First pronoun confusion",
	                              "First time asks for help by taking your hand and showing you what ${he} needs",
	                              "Reads first word",
	                              "First time eating whole fruit",
	                              "The Terrible Twos begin.",
	                              "First jigsaw puzzle",
	                              "${He} outgrows the infant car seat",
	                              "Potty training begins",
	                              "First time ${he} grabs something with both hands",
	                              "First fall where ${he} bangs ${his} head and cries ",
	                              "First time ${he} rips up magazines",
	                              "First time you explain objects that ${he} sees in front of ${him}, so ${he} can learn what they are",
	                              "First time you eat your kids spat-out food (and dont realize it)",
	                              "First time ${he} plays Ring Around the Rosie",
	                              "First time ${he} lays on a mat -- and doesnt cry",
	                              "First time ${he} asks what words mean when ${he} doesnt know",
	                              "First day of preschool!",
	                              "First time ${he} sticks out ${his} tongue in response to yours",
	                              "First time you notice ${him} making the sucking movements with ${his} mouth... while ${he}s asleep and not sucking anything",
	                              "First time you realize ${he}s Lego obsessed",
	                              "${He} is now comfortable on your hip",
	                              "First time ${he} sees you holding a friends baby. Oh, the rage!",
	                              "First time ${he} repeats your words",
	                              "First time ${his} oooh sounds turn into more self-babbling",
	                              "First trip to the zoo",
	                              "First long stroll outside (with you holding his hand)",
	                              "First time ${he} caresses moms breasts",
	                              "First time you treat ${him} like a puppet, to show tricks to your friends or family",
	                              "First broken arm",
	                              "First time you realize ${his} eyes stopped jiggling",
	                              "First time ${he} blames ${his} sibling",
	                              "First time ${he} has a favorite song",
	                              "First time ${he} follows objects with ${his} body (looking around corners)",
	                              "First puréed solid food - Failed attempt",
	                              "Cooing and trying to talk when talked to",
	                              "First boyfriend",
	                              "First time you read to ${him}",
	                              "First time ${he} wipes ${his} nose on furniture",
	                              "First time feeling the sand in ${his} toes",
	                              "First time ${he} screams in public about ${his} genitalia",
	                              "First embarrassing fart in front of other people ",
	                              "First time you realize ${he} loves peekaboo",
	                              "First time that you feel that your toddler is so frustrating, that a solo international flight is looking mighty attractive",
	                              "First time Mom takes ${him} to the doctor for no reason ",
	                              "First poopy pants accident",
	                              "First time ${he} loves Thomas the Tank Engine",
	                              "First time petting the dog without violence",
	                              "First time you bring ${him} out in a baby carrier",
	                              "First tantrum",
	                              "First baseball game",
	                              "First time ${he} watches you shower",
	                              "First time someone says ${he} looks like a famous person",
	                              "First time ${he} empties out a container (purse, box)",
	                              "First time ${he} fully holds ${his} neck up (for an extended period)",
	                              "Second bottom tooth",
	                              "First time ${he} tries to put something in ${his} mouth, when there is already something in ${his} mouth",
	                              "First time ${he} goes 7 days without poo-ing",
	                              "Started commando crawling! ",
	                              "First time wags finger at you",
	                              "First time ${he} uses a computer mouse correctly",
	                              "First time ${he} plays with a touchscreen, iPad or tablet",
	                              "Potty trained!",
	                              "First time riding in shopping cart",
	                              "Scooted on stomach across the crib",
	                              "First kiddiecoaster ride!",
	                              "First time ${he} pushes a real button (not on a toy)",
	                              "First time ${he} helps you assemble something",
	                              "First time ${he} drinks cows milk",
	                              "First time ${he} caresses your breasts",
	                              "First year check-up (aka, well-baby visit)",
	                              "First time ${he} lifts himself unaided to standing",
	                              "First time ${he} drinks formula",
	                              "First time you give ${him} a lemon.. and ${he} makes a face reacting negatively to it",
	                              "First time ${he} jumps into a puddle",
	                              "First time ${he} knows all the Thomas trains by name, color and number",
	                              "First time ${he} licks ice-cream",
	                              "First sibling fight",
	                              "First time you realize ${he} loves banging on things",
	                              "First time ${he} pees in a public toilet and doesnt get anything soiled",
	                              "First favourite teddy bear",
	                              "First time hurts ${him}self playing, then comes to you for consolation",
	                              "First time ${he} does a half-roll, half-lift",
	                              "First unexplainable meltdown in public",
	                              "First time ${he} feeds ${him}self with a spoon, possibly imitating you",
	                              "First time ${he} uses you as a human handkerchief",
	                              "First bath",
	                              "First stretch while awake",
	                              "First time you try to let ${him} cry it out -- but dont have the strength to stay out",
	                              "First time ${he} responds to a noise",
	                              "First two-word sentence",
	                              "First scraped knee",
	                              "First time Mom changes ${his} diaper",
	                              "First time ${he} picks a flower by ${him}self",
	                              "First poop in the potty!",
	                              "First gentle separation class",
	                              "First time ${he} notices people of different races and ethnicities",
	                              "First time ${he} puts the pacifier into ${his} own mouth ${him}self",
	                              "First time ${he} writes between the lines",
	                              "First time ${he} meets grandma or grandpa",
	                              "First time ${he} loves to push the doll stroller",
	                              "First time climbing a tree",
	                              "First time ${he} reacts to music",
	                              "First time playing with leaves",
	                              "First coo-ing",
	                              "First time someone says ${he} looks like a grandparent",
	                              "First time someone says ${he} looks like Dad",
	                              "First time ${his} own fart wakes ${him} up crying",
	                              "First time ${he} shows separation anxiety",
	                              "First time ${he} sees a fish in an aquarium",
	                              "First time ${he} tries the potty",
	                              "First time someone says ${he} looks like a sibling",
	                              "First time ${he} uses your body hair to pull ${him}self to standing",
	                              "First time ${he} drinks whole milk",
	                              "First time ${he} lets out a devilish laugh ",
	                              "First time cutting ${his} finger nails",
	                              "First time ${he} knows the months of the year",
	                              "First time ${he} fake brushes ${his} teeth",
	                              "First time uses an umbrella",
	                              "First time ${he} waves bye bye",
	                              "First time ${he} throws something to the ground... and waits for a reaction",
	                              "First hiccup attack",
	                              "${He} lost ${his} umbilical cord",
	                              "First time ${he} waves back to you",
	                              "First one minute stand",
	                              "First time ${he} has a best friend",
	                              "First full smile ",
	                              "First beat-boxing (learnt from watching Yo Gabba Gabba!)",
	                              "${He} knows a few letters and numbers",
	                              "First time baby tugs a friends beard",
	                              "First time your child falls asleep while eating",
	                              "First time ${he} wears gloves",
	                              "First time baby makes dad very nervous climbing on stuff",
	                              "First time ${he} shakes, almost dances, to music",
	                              "First time ${he} tells a story. (Mostly true)",
	                              "First high ten",
	                              "Says YES perfectly",
	                              "First time ${he} sits upright with assistance",
	                              "First time riding on your shoulders, holding only ${his} legs",
	                              "First time you realize ${his} eyes stopped crossing",
	                              "First time riding a tricycle",
	                              "First time ${he} gets off the couch all by ${him}self, properly",
	                              "First time she loves baby dolls",
	                              "First hug (from ${him}) ",
	                              "First sibling hug",
	                              "First sibling kiss",
	                              "First time ${he} cries for your attention even when ${he} has it",
	                              "First time ${he} eats a book",
	                              "First time opens door by ${him}self",
	                              "First time you notice ${his} poop changing color",
	                              "First time you notice the food that ${he} ate in ${his} poo",
	                              "First time goes down the slide without help",
	                              "${He} loses the tongue thrust reflex",
	                              "First time ${he} tries to eat ${his} own feet",
	                              "First stitches!",
	                              "First time eating bread",
	                              "First time sitting on your knees",
	                              "First time you almost trip while walking holding ${him} in your arms",
	                              "First time ${he} has Baby Radar to sense other babies and realizes theres something similar about them. Yes, Just like dogs.",
	                              "First time ${he} sits up without anyones help -- for more than 5 seconds",
	                              "First photo of ${him}",
	                              "First time ${he} counts to ten",
	                              "${His} first train set",
	                              "First drive in the car to calm ${him} down",
	                              "First time ${he} can identify the sequence of elaborate patterns",
	                              "First time ${he} falls asleep while drinking from Moms breast",
	                              "First scrambled egg without puking",
	                              "Took a bath with daddy ",
	                              "First time ${he} bites ${his} sibling",
	                              "First time furniture surfing",
	                              "First time ${he} touches ${his} own feet",
	                              "First time ${he} starts shoving food in the electronics",
	                              "First time ${he} gets Peekaboo",
	                              "First time someone says ${he} looks like Mom",
	                              "First time ${he} pulls ${him}self to standing in crib",
	                              "First time ${he} throws a ball",
	                              "First cold ",
	                              "First time ${he} really laughs, not giggles",
	                              "First time eating nuts",
	                              "First time taking ${his} clothes entirely off to use the bathroom",
	                              "First time ${he} holds a pencil correctly",
	                              "First time ${he} freaks out from fireworks",
	                              "First time ${he} sorts things by shape and color",
	                              "First time ${he} spontaneously hugs you",
	                              "First time ${he} regularly puts individual words together into two-word phrases",
	                              "First time ${he} lifts ${his} head up while laying down: doing the mini-push-up",
	                              "First time ${he} stands up without support",
	                              "First time you leave ${him} on your bed, surrounded by a Pillow Wall",
	                              "First derp photo bomb ",
	                              "First time ${he} rolls over back to front",
	                              "First time ${he} screams in public places, and enjoys your reaction!",
	                              "First time ${he} plays in a toy kitchen",
	                              "First time ${he} opens ${his} eyes wide",
	                              "First time ${he} feeds YOU.",
	                              "First time ${he} eats meat",
	                              "First high five",
	                              "First time you notice ${he}s no longer cross-eyed",
	                              "First time you play a joke on ${him}. ${He} doesnt get it.",
	                              "First picture with mom",
	                              "First time you can hold ${him} without propping ${his} neck up",
	                              "First time ${his} skin appears to have the normal color, not the ball of red ${he} was probably born as",
	                              "First time you freak out over nothing",
	                              "First time ${he} gets pinkeye",
	                              "First time trick-or-treating for Halloween",
	                              "First taste of toothpaste",
	                              "First time you realize ${he} can talk in complex sentences",
	                              "First time you play peekaboo... but ${he} doesnt get it",
	                              "First time you think, Wow, ${he}s a real person!",
	                              "First almost sit-up all alone, even if just for a second.",
	                              "First time riding in a laundry basket",
	                              "First time tries to put keys into the lock",
	                              "First time using a bow on her head",
	                              "First time ${he} loves water balloons and water play in general",
	                              "First time ${he} meets another child of the same name",
	                              "Felt rain for the first time and laughed ",
	                              "${He} eats school lunch for the first and, often, the last time",
	                              "First time ${he} cries just because ${he} hears someone else crying",
	                              "First time you wonder, Is ${he} retarded?",
	                              "First Staycation with mom",
	                              "${He} is weaned",
	                              "First time ${he} sleeps 6 hours without interruption",
	                              "First sibling laughing together",
	                              "First time ${he} loves fire trucks",
	                              "First time she knows all princesses by name, dress color, and kingdom",
	                              "First video-conference with ${him} crying in the background... or on your lap",
	                              "First time ${he} opens something that is childproofed",
	                              "First time ${he} sleeps more than 9 hours straight",
	                              "First time you realize ${he} loves playing in cardboard boxes",
	                              "First time ${he} stoops to pick up something while standing",
	                              "First time ${he} says dad, dada, or some variation",
	                              "First time drinks from cup by ${him}self",
	                              "${He} just about says ${his} first word: perhaps accidentally or perhaps practice",
	                              "First time ${he} see’s snowfall",
	                              "First time ${he} throws something to the ground",
	                              "Ate green beans for the first time",
	                              "First standing up on ${his} own - with support",
	                              "First time getting a straw through the hole in a cup",
	                              "${His} first real kiss to you!",
	                              "First time ${he} rocks himself in a rocking chair",
	                              "First time ${he} can peel a banana",
	                              "First time ${he} tells you ${he} farted by waving his hand while saying …uuewwwww",
	                              "First time ${he} burst out crying when ${he} heard someone else sneeze",
	                              "First time ${he} sight reads words",
	                              "First time deliberately pees on the bed",
	                              "First fart in moms face",
	                              "First time in excesaucer",
	                              "First time cries because you wont let ${him} eat something ",
	                              "First time ${his} poo is green",
	                              "First time picking strawberries",
	                              "First walk in the rain ",
	                              "First puréed solid food - Success!",
	                              "First time ${he} tells stories (only sometimes true)",
	                              "First time talking in short sentences",
	                              "First time you catch vomit in your cupped hands",
	                              "First time stands on ${his} own, without support",
	                              "${His} first sushi",
	                              "First time pointing to you or another object",
	                              "First time ${he} spins in a circle while sitting",
	                              "First ‘Piggy Bank’",
	                              "First time smells a flower by ${him}self",
	                              "First time ${he} sat up, alone, for more than 10 seconds",
	                              "First time ${he} says dad clearly and not accidentally",
	                              "First time you realize that ${he} can move ${his} eyes all the way in both directions",
	                              "First time meets older sibling",
	                              "First trip to the planetarium",
	                              "First time hums along to music",
	                              "First time ${he} reaches for your breast",
	                              "First poo in a baby potty ",
	                              "${He} pulls to stand.",
	                              "First time ${he} feels a complex emotion",
	                              "First time ${he} tries to join in an adult conversation",
	                              "First time connecting Lego blocks",
	                              "First frenemy",
	                              "First time ${he} drinks from a (non-sippy) cup - with help",
	                              "First use of both hands in coordination with each other",
	                              "First time ${he} wears your shoes and looks better in them than you do",
	                              "First time ${he} plays with baby dolls",
	                              "First time ${he} refuses to put on shoes and socks",
	                              "First time ${he} completes first peg puzzle",
	                              "First orange-peel smile",
	                              "First time says hot when touching something hot",
	                              "First time ${he}, upon seeing a stranger, turns to hug Mom or Dad",
	                              "First time ${he} makes noises talking to ${him}self while sleeping -- and you go check in on ${him} but ${he}s fast asleep",
	                              "First time ${he} draws a person",
	                              "First time ${he} shows the moro reflex",
	                              "First time ${he} starts eating two meals/day",
	                              "First time ${he} grasps a toy",
	                              "First time ${he} recognizes Dad",
	                              "First contagious yawn between you two",
	                              "First full length movie",
	                              "Sits up and plays by ${him}self",
	                              "First hangs from a bar",
	                              "First time ${he} says bye-bye (or ba-ba)",
	                              "First time ${he} brags about what ${he} does at school",
	                              "First 10 assisted steps",
	                              "First time you realize ${he} can somehow drink milk while sleeping simultaneously",
	                              "First time ${he} understands when you tell ${him} a strong, NO!",
	                              "First whistle",
	                              "First time points to something and says the word for it",
	                              "First time youre playing with ${him}... and ${he} cries for no reason",
	                              "First time ${he} plays with ${his} own feet",
	                              "Learns how to jump",
	                              "Not liking ${his} shirt",
	                              "First time ${he} knows basic shapes",
	                              "First time ${he} wears size 6-9mos",
	                              "First time ${he} grabs Dads hair",
	                              "First time ${he} orders ${his} own food in a restaurant",
	                              "First time ${he} bends ${his} knees to sit",
	                              "First time ${he} uses the raking grasp style of trying to grab things",
	                              "First time ice skating!",
	                              "First time ${he} wears a baseball cap outside the house",
	                              "First visit to nursery",
	                              "First time ${he} hates walking on uneven surfaces",
	                              "First time you notice that ${he}s pretty good at walking",
	                              "First time blowing bubbles",
	                              "First birthday cake",
	                              "First time ${he} falls off your bed",
	                              "First time ${he} writes you a letter",
	                              "First flirt with the cute waitress",
	                              "First time ${he} finds ${his} toes",
	                              "First time you see one of your partners characteristics in ${him}",
	                              "First time Mom can differentiate ${his} cries",
	                              "First time ${he} rejects the pacifier",
	                              "First time ${he} wears 12mos sized clothing",
	                              "First time eating a banana (not mashed)",
	                              "First time ${he} walks sideways, holding on to something",
	                              "First time ${his} eyes track you as you move around the room",
	                              "First time ${he} pees on Dad",
	                              "First time ${he} kisses everybody (on the mouth)",
	                              "First time you realize that the distraction method works to stop ${his} crying",
	                              "First vaccinations ",
	                              "First time you have a mini-breakdown",
	                              "First time ${he} enjoys fireworks",
	                              "First time ${he} sleeps 5 hours without interruption",
	                              "First kiss (from ${him})",
	                              "First time ${he} is terrified of Santa Claus",
	                              "First time eating a full banana",
	                              "First time ${he} does the Penguin Pivot",
	                              "First time ${he} imitates TV characters",
	                              "First time ${he} recognizes someone ${he} see regularly, other than Mom and Dad",
	                              "First time ${he} reaches for something (other than your breast)",
	                              "First time ${he} runs like a flat-footed oompa-loompa",
	                              "First time ${he} picks up remote and aims it at the television ",
	                              "First time ${he} falls asleep on you -- and you also fall asleep",
	                              "First time scooting backwards on stomach: failed push-up",
	                              "First time playing on jungle gym with help",
	                              "First time ${he} plays hide and seek",
	                              "First time ${he} bumps his head",
	                              "First fancy dress costume",
	                              "First time sayin down very clearly",
	                              "First time ${he} announces ${his} poops",
	                              "First time you have sex with Mom after ${his} birth",
	                              "First time ${his} head moves to follow you as you move, for just a little bit.",
	                              "First time ${he} pees on you",
	                              "First time sucking ${his} thumb",
	                              "Takes off ${his} diaper!",
	                              "First time ${he} drinks from a (non-sippy) cup - without help",
	                              "First time ${he} purposely takes out ${his} pacifier so ${he} can put something else into ${his} mouth",
	                              "First time unzips a zipper",
	                              "First fake cry",
	                              "First time ${he} gets scared of the automatic flush and dryers in public bathrooms",
	                              "First time you notice what ${his} hair color is turning out to be",
	                              "First time ${he} draws representationally (such as, cars or planes)",
	                              "First non-relative takes care of ${him}, alone",
	                              "First time ${he} tastes a splash of food on ${his} tongue",
	                              "First Christmas",
	                              "First time ${he} cries with lots and lots of tears, running down ${his} face",
	                              "First time you think you never want another baby",
	                              "First time ${he} tries to comb ${his} hair",
	                              "First time ${he} bounces in place when ${he} really likes the music!",
	                              "${He} discovers stickers",
	                              "First time ${he} talks like a little person",
	                              "First time ${he} differentiates strangers from people ${he} knows",
	                              "Says please and thank you reliably",
	                              "First time you realize that ${he} really loves standing up (even if ${he} can barely stand)",
	                              "First bagel",
	                              "First time imitates an animal sound",
	                              "First time ${he} grabs something and wont let go",
	                              "First 3 consecutive hours of sleep",
	                              "First time ${he} grabs Moms hair",
	                              "First time stranger touches ${him} and you think, Why the hell are you putting your dirty hands onto my baby?",
	                              "First New Years Eve",
	                              "First time tastes something spicy",
	                              "Circumcision",
	                              "First sleep through the night",
	                              "First time ${he} discovered splashing!",
	                              "First time Mom says, Did you wash your hands? when youre about to touch ${him}",
	                              "First fever",
	                              "First snore ",
	                              "First haircut",
	                              "First gift",
	                              "First time ${he} hops on one foot",
	                              "First real birthday party",
	                              "First time teething",
	                              "First time ${he} reverses syllables of words",
	                              "First time operates the CD in the car",
	                              "First time ${his} face or eyes completely follow you all around the room",
	                              "First time ${he} recognizes ${him}self in the mirror",
	                              "First time plays with a toy car",
	                              "First time ${he} took ${his} jacket off all by himself",
	                              "First time ${he} grabs a knife off the table",
	                              "First time you wear matching clothing",
	                              "First fight",
	                              "First time bowling",
	                              "You realise the house is empty without ${him}",
	                              "First time ${he} sleeps in your bed",
	                              "First time Mom has a mini breakdown");
	
	public static Hashtable<String,Integer> compareAllStrings(ArrayList<String> listOfStrings){
		ArrayList<String> newList = new ArrayList<String>(listOfStrings);
		Hashtable<String,Integer> titleToCountOfMatches=new Hashtable<String,Integer>();
		for(Iterator<String> iter1 = newList.iterator(); iter1.hasNext(); ){
			String title1 = iter1.next();
			iter1.remove();
			for(Iterator<String> iter2 = newList.iterator(); iter2.hasNext(); ){
				String title2 = iter2.next();
				double sim=getSimilarity(title1,title2);
				if(sim>0.85){
					//iter2.remove();
					//Causes an error
					if(titleToCountOfMatches.containsKey(title1)){
						titleToCountOfMatches.put(title1, titleToCountOfMatches.get(title1)+1);
					}
					else{
						titleToCountOfMatches.put(title1,1);
					}
				}
			}
		}
		return titleToCountOfMatches;
	}
	
	public static void main(String[] args) {
		Parse.initialize("NlJHBG0NZgFS8JP76DBjA31MBRZ7kmb7dVSQQz3U", "B8DK9s4WkHzujVxmfLEDUS7CWqUje29GhOPZMAtY");
		getStandardTitles();
		//getCustomMilestones();
	}
}
